// @ts-check
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    // {
    //   type: 'category',
    //   label: 'Hackathons',
    //   items: [
    //     {
    //       type: 'category',
    //       label: 'Current Hackathons',
    //       items: ['hackathons/Current/eth-denver-hackathon'], // Path from the 'docs' directory, without the file extension
    //     },
    //     {
    //       type: 'category',
    //       label: 'Previous Hackathons',
    //       items: ['hackathons/Previous/eth-lisbon-hackathon'], // Path from the 'docs' directory, without the file extension
    //     },
    //   ],
    // },
    // Other sidebar items or categories
    {
      type: 'autogenerated',
      dirName: '.', // Automatically generate the rest of the sidebar based on the docs folder structure
    },
  ],
};

export default sidebars;

