#!/usr/bin/env bash

cd $(git rev-parse --show-toplevel)
rm -fr tmp/chronicles

# NOTE you need to have your Github auth setup or this will fail
git clone https://github.com/chronicleprotocol/chronicles.git tmp/chronicles

python scripts/stage-oracles/generate.py > ./docs/Developers/testnet.md
git status
